name: FreeBSD build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'  # Every Saturday at 4am

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: FreeBSD build
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: |
          pkg install -y gmake libX11 mesa-libs libglvnd libGLU

        run: |
          ./configure
          gmake
          gmake DESTDIR=libspnav-freebsd install
          gmake examples
          mkdir libspnav-freebsd/examples
          cp examples/simple/simple_af_unix libspnav-freebsd/examples
          cp examples/simple/simple_x11 libspnav-freebsd/examples
          cp examples/cube/cube libspnav-freebsd/examples
          cp examples/fly/fly libspnav-freebsd/examples

    - uses: actions/upload-artifact@v4
      with:
        name: libspnav-freebsd
        path: libspnav-freebsd

# vi:ts=2 sts=2 sw=2 expandtab:
